<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TemplateCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // ─── Invoice Templates ─────────────────────────────────────
            [
                'code' => 'invoice-default',
                'name' => 'Modèle 1',
                'slug' => 'invoice-modele-1',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Modèle de facture par défaut, propre et professionnel.',
                'view_path' => 'pdf.templates.free.invoice.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/invoice/model-1.png',
            ],
            [
                'code' => 'invoice-modern',
                'name' => 'Modèle 2',
                'slug' => 'invoice-modele-2',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Design moderne avec en-tête coloré et mise en page contemporaine.',
                'view_path' => 'pdf.templates.free.invoice.model-2',
                'price' => 0,
                'is_free' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'preview_image' => 'assets/images/templates/invoice/model-2.png',
            ],
            [
                'code' => 'invoice-classic',
                'name' => 'Modèle 3',
                'slug' => 'invoice-modele-3',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Style classique avec bordures et structure traditionnelle.',
                'view_path' => 'pdf.templates.free.invoice.model-3',
                'price' => 0,
                'is_free' => true,
                'is_featured' => false,
                'sort_order' => 3,
                'preview_image' => 'assets/images/templates/invoice/model-3.png',
            ],
            [
                'code' => 'invoice-elegant',
                'name' => 'Modèle 4',
                'slug' => 'invoice-modele-4',
                'document_type' => 'invoice',
                'category' => 'general',
                'description' => 'Design élégant avec dégradés et typographie raffinée.',
                'view_path' => 'pdf.templates.free.invoice.model-4',
                'price' => 0,
                'is_free' => true,
                'is_featured' => false,
                'sort_order' => 4,
                'preview_image' => 'assets/images/templates/invoice/model-4.png',
            ],

            // ─── Quote Templates ───────────────────────────────────────
            [
                'code' => 'quote-default',
                'name' => 'Modèle 1',
                'slug' => 'quote-modele-1',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Modèle de devis par défaut.',
                'view_path' => 'pdf.templates.free.quote.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/quote/model-1.png',
            ],
            [
                'code' => 'quote-modern',
                'name' => 'Modèle 2',
                'slug' => 'quote-modele-2',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Devis au design moderne.',
                'view_path' => 'pdf.templates.free.quote.model-2',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'assets/images/templates/quote/model-2.png',
            ],
            [
                'code' => 'quote-classic',
                'name' => 'Modèle 3',
                'slug' => 'quote-modele-3',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Devis au style classique.',
                'view_path' => 'pdf.templates.free.quote.model-3',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 3,
                'preview_image' => 'assets/images/templates/quote/model-3.png',
            ],
            [
                'code' => 'quote-elegant',
                'name' => 'Modèle 4',
                'slug' => 'quote-modele-4',
                'document_type' => 'quote',
                'category' => 'general',
                'description' => 'Devis au design élégant.',
                'view_path' => 'pdf.templates.free.quote.model-4',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 4,
                'preview_image' => 'assets/images/templates/quote/model-4.png',
            ],

            // ─── Credit Note Templates ─────────────────────────────────
            [
                'code' => 'credit-note-default',
                'name' => 'Modèle 1',
                'slug' => 'credit-note-modele-1',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => "Modèle d'avoir par défaut.",
                'view_path' => 'pdf.templates.free.credit-note.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/credit-note/model-1.png',
            ],
            [
                'code' => 'credit-note-modern',
                'name' => 'Modèle 2',
                'slug' => 'credit-note-modele-2',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => 'Avoir au design moderne.',
                'view_path' => 'pdf.templates.free.credit-note.model-2',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'assets/images/templates/credit-note/model-2.png',
            ],
            [
                'code' => 'credit-note-classic',
                'name' => 'Modèle 3',
                'slug' => 'credit-note-modele-3',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => 'Avoir au style classique.',
                'view_path' => 'pdf.templates.free.credit-note.model-3',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 3,
                'preview_image' => 'assets/images/templates/credit-note/model-3.png',
            ],
            [
                'code' => 'credit-note-elegant',
                'name' => 'Modèle 4',
                'slug' => 'credit-note-modele-4',
                'document_type' => 'credit_note',
                'category' => 'general',
                'description' => 'Avoir au design élégant.',
                'view_path' => 'pdf.templates.free.credit-note.model-4',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 4,
                'preview_image' => 'assets/images/templates/credit-note/model-4.png',
            ],

            // ─── Delivery Challan Templates ────────────────────────────
            [
                'code' => 'delivery-challan-default',
                'name' => 'Modèle 1',
                'slug' => 'delivery-challan-modele-1',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Modèle de bon de livraison par défaut.',
                'view_path' => 'pdf.templates.free.delivery-challan.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/delivery-challan/model-1.png',
            ],
            [
                'code' => 'delivery-challan-modern',
                'name' => 'Modèle 2',
                'slug' => 'delivery-challan-modele-2',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Bon de livraison au design moderne.',
                'view_path' => 'pdf.templates.free.delivery-challan.model-2',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'assets/images/templates/delivery-challan/model-2.png',
            ],
            [
                'code' => 'delivery-challan-classic',
                'name' => 'Modèle 3',
                'slug' => 'delivery-challan-modele-3',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Bon de livraison au style classique.',
                'view_path' => 'pdf.templates.free.delivery-challan.model-3',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 3,
                'preview_image' => 'assets/images/templates/delivery-challan/model-3.png',
            ],
            [
                'code' => 'delivery-challan-elegant',
                'name' => 'Modèle 4',
                'slug' => 'delivery-challan-modele-4',
                'document_type' => 'delivery_challan',
                'category' => 'general',
                'description' => 'Bon de livraison au design élégant.',
                'view_path' => 'pdf.templates.free.delivery-challan.model-4',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 4,
                'preview_image' => 'assets/images/templates/delivery-challan/model-4.png',
            ],

            // ─── Purchase Order Templates ──────────────────────────────
            [
                'code' => 'purchase-order-default',
                'name' => 'Modèle 1',
                'slug' => 'purchase-order-modele-1',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Modèle de bon de commande par défaut.',
                'view_path' => 'pdf.templates.free.purchase-order.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/purchase-order/model-1.png',
            ],
            [
                'code' => 'purchase-order-modern',
                'name' => 'Modèle 2',
                'slug' => 'purchase-order-modele-2',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Bon de commande au design moderne.',
                'view_path' => 'pdf.templates.free.purchase-order.model-2',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 2,
                'preview_image' => 'assets/images/templates/purchase-order/model-2.png',
            ],
            [
                'code' => 'purchase-order-classic',
                'name' => 'Modèle 3',
                'slug' => 'purchase-order-modele-3',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Bon de commande au style classique.',
                'view_path' => 'pdf.templates.free.purchase-order.model-3',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 3,
                'preview_image' => 'assets/images/templates/purchase-order/model-3.png',
            ],
            [
                'code' => 'purchase-order-elegant',
                'name' => 'Modèle 4',
                'slug' => 'purchase-order-modele-4',
                'document_type' => 'purchase_order',
                'category' => 'general',
                'description' => 'Bon de commande au design élégant.',
                'view_path' => 'pdf.templates.free.purchase-order.model-4',
                'price' => 0,
                'is_free' => true,
                'sort_order' => 4,
                'preview_image' => 'assets/images/templates/purchase-order/model-4.png',
            ],

            // ─── Vendor Bill Templates ────────────────────────────────
            [
                'code' => 'vendor-bill-default',
                'name' => 'Modèle 1',
                'slug' => 'vendor-bill-modele-1',
                'document_type' => 'vendor_bill',
                'category' => 'general',
                'description' => 'Modèle de facture fournisseur par défaut.',
                'view_path' => 'pdf.templates.free.vendor-bill.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/vendor-bill/model-1.png',
            ],

            // ─── Debit Note Templates ─────────────────────────────────
            [
                'code' => 'debit-note-default',
                'name' => 'Modèle 1',
                'slug' => 'debit-note-modele-1',
                'document_type' => 'debit_note',
                'category' => 'general',
                'description' => 'Modèle de note de débit par défaut.',
                'view_path' => 'pdf.templates.free.debit-note.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/debit-note/model-1.png',
            ],

            // ─── Payment Receipt Templates ────────────────────────────
            [
                'code' => 'payment-receipt-default',
                'name' => 'Modèle 1',
                'slug' => 'payment-receipt-modele-1',
                'document_type' => 'payment_receipt',
                'category' => 'general',
                'description' => 'Modèle de reçu de paiement par défaut.',
                'view_path' => 'pdf.templates.free.payment-receipt.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/payment-receipt/model-1.png',
            ],

            // ─── Supplier Payment Receipt Templates ───────────────────
            [
                'code' => 'supplier-payment-receipt-default',
                'name' => 'Modèle 1',
                'slug' => 'supplier-payment-receipt-modele-1',
                'document_type' => 'supplier_payment_receipt',
                'category' => 'general',
                'description' => 'Modèle de reçu de paiement fournisseur par défaut.',
                'view_path' => 'pdf.templates.free.supplier-payment-receipt.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/supplier-payment-receipt/model-1.png',
            ],

            // ─── Goods Receipt Templates ──────────────────────────────
            [
                'code' => 'goods-receipt-default',
                'name' => 'Modèle 1',
                'slug' => 'goods-receipt-modele-1',
                'document_type' => 'goods_receipt',
                'category' => 'general',
                'description' => 'Modèle de bon de réception par défaut.',
                'view_path' => 'pdf.templates.free.goods-receipt.model-1',
                'price' => 0,
                'is_free' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'preview_image' => 'assets/images/templates/goods-receipt/model-1.png',
            ],

        ];

        foreach ($templates as $tpl) {
            DB::table('template_catalog')->updateOrInsert(
                ['code' => $tpl['code']],
                array_merge($tpl, [
                    'id' => DB::table('template_catalog')->where('code', $tpl['code'])->value('id') ?? Str::uuid()->toString(),
                    'engine' => 'blade',
                    'currency' => 'MAD',
                    'version' => '1.0.0',
                    'is_active' => true,
                    'is_featured' => $tpl['is_featured'] ?? false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
