<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="@yield('meta_description', config('app.name') . ' — Logiciel de facturation et gestion commerciale en ligne')">
		<meta name="author" content="{{ config('app.name', 'Hssabek') }}">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<title>@yield('title', 'Accueil') | {{ config('app.name', 'Hssabek') }}</title>

		<!-- Favicons (generated by realfavicongenerator) -->
		<link rel="icon" type="image/png" href="/assets/images/favicon/favicon-96x96.png" sizes="96x96" />
		<link rel="icon" type="image/svg+xml" href="/assets/images/favicon/favicon.svg" />
		<link rel="shortcut icon" href="/assets/images/favicon/favicon.ico" />
		<link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon/apple-touch-icon.png" />
		<meta name="apple-mobile-web-app-title" content="Hssabek" />
		<link rel="manifest" href="/assets/images/favicon/site.webmanifest" />

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url('build/css/bootstrap.min.css') }}">

		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{{ url('build/plugins/fontawesome/css/fontawesome.min.css') }}">
		<link rel="stylesheet" href="{{ url('build/plugins/fontawesome/css/all.min.css') }}">

		<!-- Aos CSS -->
		<link rel="stylesheet" href="{{ url('build/plugins/aos/aos.css') }}">

		<!-- Owl carousel CSS -->
		<link rel="stylesheet" href="{{ url('build/css/owl.carousel.min.css') }}">

		<!-- Feather CSS -->
		<link rel="stylesheet" href="{{ url('build/css/feather.css') }}">

		<!-- Iconsax CSS -->
		<link rel="stylesheet" href="{{ url('build/css/iconsax.css') }}">

		<!-- Landing CSS -->
		<link rel="stylesheet" href="{{ url('build/css/landing.css') }}">

		@if(app()->getLocale() === 'ar')
		<style>
			/* ===== RTL for Arabic — text direction only, layout stays LTR ===== */

			/* --- Base text direction --- */
			h1, h2, h3, h4, h5, h6, p, li, span, a, label, td, th, dt, dd,
			.section-title, .section-text, .footer-content, .footer-widget,
			.template-info, .copy-right, .footer-bottom-widget,
			.banner-content, .feature-content, .pricing-card,
			.card-body, .card-header, .card-footer,
			.about-content, .counter-content, .faq-content,
			.contact-content, .hero-content, .breadcrumb-item,
			.dropdown-item, .dropdown-menu, .nav-link,
			input, textarea, select, .form-control, .form-label,
			.invalid-feedback, .alert,
			.managing-info, .empowerment-page-info, .saas-information,
			.module-card, .packages-card, .software-sec-info {
				direction: rtl;
				text-align: right;
			}

			/* --- Keep centered elements centered --- */
			.text-center, .text-center h1, .text-center h2, .text-center h3,
			.text-center h4, .text-center h5, .text-center h6, .text-center p,
			.text-center span, .text-center a,
			.section-title.text-center, .text-center .section-title {
				text-align: center !important;
			}

			/* --- Section headings (flexbox centered) --- */
			.section-heading { direction: ltr; }
			.section-heading h2, .section-heading p, .section-heading span,
			.section-heading .title-badge {
				direction: rtl;
				text-align: center !important;
			}
			/* Section heading inside FAQ (left-aligned, not centered) */
			.faq-section .col-lg-5 .section-heading h2,
			.faq-section .col-lg-5 .section-heading p,
			.faq-section .col-lg-5 .section-heading span,
			.faq-section .col-lg-5 .section-heading .title-badge,
			.software-sec-info .section-heading h2,
			.software-sec-info .section-heading p,
			.software-sec-info .section-heading span,
			.software-sec-info .section-heading .title-badge {
				text-align: right !important;
			}

			/* --- Centered flex containers stay LTR --- */
			.d-flex.justify-content-center { direction: ltr; }

			/* --- Navbar: layout LTR, text RTL --- */
			.header-nav, .main-nav, .header-navbar-rht { direction: ltr; }
			.main-nav > li > a, .header-navbar-rht .btn,
			.header-navbar-rht .dropdown-item { direction: rtl; }

			/* --- Dropdown menus --- */
			.dropdown-menu { text-align: right; }
			.header-navbar-rht .dropdown-menu { left: 0; right: auto; }

			/* --- Icon + text spacing (flip me-X to ms-X) --- */
			.btn .me-1 { margin-right: 0 !important; margin-left: 0.25rem !important; }
			.btn .me-2 { margin-right: 0 !important; margin-left: 0.5rem !important; }
			.btn .ms-2 { margin-left: 0 !important; margin-right: 0.5rem !important; }
			li i.me-1, li i.me-2 { margin-right: 0 !important; }
			li i.me-1 { margin-left: 0.25rem !important; }
			li i.me-2 { margin-left: 0.5rem !important; }

			/* --- Banner info list (checkmarks) --- */
			.banner-info-list li { margin-right: 0; margin-left: 40px; }
			.banner-info-list li:last-child { margin-left: 0; }
			.banner-info-list li i { margin-right: 0; margin-left: 8px; }

			/* --- App cards (icon left of text) --- */
			.app-card .app-icon { margin-right: 0; margin-left: 16px; }

			/* --- Plan features list (icon + text) --- */
			.plan-features li i { margin-right: 0; margin-left: 8px; }

			/* --- Inner page feature list --- */
			.inner-page-features li i { margin-right: 0; margin-left: 8px; }

			/* --- Business info list (checkmarks) --- */
			.bussiness-info li i { margin-right: 0 !important; margin-left: 8px !important; }

			/* --- FAQ accordion icon: move from right to left --- */
			.faq-set .faq-card h4 a { padding-right: 0; padding-left: 30px; }
			.faq-set .faq-card h4 a::before { right: auto; left: 0; }

			/* --- Management cards (software section) --- */
			.management-types .mnaging-icon { margin-right: 0; margin-left: 16px; }

			/* --- Module cards --- */
			.module-card .module-icon { margin-bottom: 16px; }

			/* --- Stats (counter sup) --- */
			.app-more-info li h4 sup { margin-left: 0; margin-right: 8px; }

			/* --- Footer --- */
			.footer-middle .row { direction: ltr; }
			.footer-widget ul { padding-right: 0; list-style: none; }

			/* --- Form inputs --- */
			.email-form input { direction: rtl; }
			.form-control, .form-select { text-align: right; }

			/* --- Tab buttons (features/pricing tabs) --- */
			.nav-pills .nav-link, .inner-tab-button .nav-link { direction: rtl; text-align: right; }

			/* --- Connect CTA section centered --- */
			.connect-with-us .section-title h2,
			.connect-with-us .section-title p {
				text-align: center !important;
			}

			/* --- Pricing package header fix --- */
			.package-header { direction: ltr; }
			.package-header h4, .package-header h6 { direction: rtl; text-align: right; }

			/* --- Start business section centered --- */
			.start-bussiness .section-title h2,
			.start-bussiness .section-title p {
				text-align: center !important;
			}

			/* --- Counter section --- */
			.counter { direction: ltr; }
		</style>
		@endif

		@stack('styles')
	</head>

<body>

	<div class="main-wrapper">

		@hasSection('hero')
		<div class="main-banner">
			@include('frontoffice.components.navbar')
			@yield('hero')
		</div>
		@else
			@include('frontoffice.components.navbar')
		@endif

		<div data-bs-spy="scroll" data-bs-target="#scroll-nav" class="scrollspy-example" tabindex="0">
			@yield('content')
			@include('frontoffice.components.footer')
		</div>

		<div class="mouse-cursor cursor-outer"></div>
		<div class="mouse-cursor cursor-inner"></div>

		<div class="back-to-top">
			<a class="back-to-top-icon align-items-center justify-content-center d-flex" href="#top"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
		</div>
	</div>

	<!-- jQuery -->
	<script src="{{ url('build/js/jquery-3.7.1.min.js') }}"></script>

	<!-- Bootstrap Core JS -->
	<script src="{{ url('build/js/bootstrap.bundle.min.js') }}"></script>
	<script src="{{ url('build/js/bootstrap-scrollspy.js') }}"></script>

	<!-- Feather JS -->
	<script src="{{ url('build/js/feather.min.js') }}"></script>

	<!-- Aos -->
	<script src="{{ url('build/plugins/aos/aos.js') }}"></script>

	<!-- counterup JS -->
	<script src="{{ url('build/js/jquery.waypoints.js') }}"></script>
	<script src="{{ url('build/js/jquery.counterup.min.js') }}"></script>

	<!-- Owl Carousel JS -->
	<script src="{{ url('build/js/owl.carousel.min.js') }}"></script>

	<!-- Custom JS -->
	<script src="{{ url('build/js/landing-script.js') }}"></script>

	<!-- Newsletter AJAX -->
	<script>
	$(function() {
		$('#newsletter-form').on('submit', function(e) {
			e.preventDefault();
			var $form = $(this), $btn = $('#newsletter-btn'), $msg = $('#newsletter-msg');
			$btn.prop('disabled', true).text('...');
			$msg.hide();
			$.ajax({
				url: $form.attr('action'),
				method: 'POST',
				data: $form.serialize(),
				dataType: 'json',
				success: function(res) {
					$msg.removeClass('text-danger').addClass('text-success').text(res.message).show();
					$form.find('input[name="email"]').val('');
				},
				error: function(xhr) {
					var msg = 'Une erreur est survenue.';
					if (xhr.responseJSON && xhr.responseJSON.errors && xhr.responseJSON.errors.email) {
						msg = xhr.responseJSON.errors.email[0];
					} else if (xhr.responseJSON && xhr.responseJSON.message) {
						msg = xhr.responseJSON.message;
					}
					$msg.removeClass('text-success').addClass('text-danger').text(msg).show();
				},
				complete: function() {
					$btn.prop('disabled', false).text("{{ __("S'abonner") }}");
				}
			});
		});
	});
	</script>

	@stack('scripts')
</body>
</html>
